### ISSUE TITLE
How to get initialize_mixture_latent_vector?

### ISSUE THREAD

**Issue by QtEngineer** [edgar-tr/patchnets#3]
initialization_file = sdf_filename + "_init_" + str(patch_latent_size) + "_" + str(num_patches) + "_" + str(surface_sdf_threshold) + "_" + str(final_scaling_increase_factor) + ("_tiny" if use_tiny_patchnet else "") + ".npy"

but there's no  such file or directory: 'datasets/shapenet_v2/preprocessed/SdfSamples/ShapeNetV2/04554684/1a23fdbb1b6d4c53902c0a1a69e25bd9.npz_init_128_30_0.02_1.2.npy'
(only have  1a23fdbb1b6d4c53902c0a1a69e25bd9.npz)

**Comment by edgar-tr** [comment]
Hi,

I don't fully remember. The readme says this:

"For all_implicit/object latents, please set |sdf_filename| under 
|use_precomputed_bias_init| in |deep_sdf_decoder.py| to an |.npz| file 
that was obtained via Preprocessing and for which 
|initialize_mixture_latent_vector()| from |train_deep_sdf.py| has been 
run (e.g. by including it in the training set and training a normal 
PatchNet). |MixtureCodeLength| is the object latent size and 
|PatchCodeLength| is the size of each of the regressed patch codes."

So including the shape in the training set and starting to train a 
normal PatchNet. That should generate that init file. Does that help?

**Comment by QtEngineer** [comment]
Excuse me,
According to readme ,  I want to know whether the origin code  in fuction initialize_mixture_latent_vector ,|deep_sdf_decoder.py|
“ if mixture_latent_mode == "【all_implicit】 ":return torch.zeros((1, specs["MixtureCodeLength"]))” correct？
I tried to change it to 【all_explict】,but there's still some run error

**Comment by edgar-tr** [comment]
What error do you get?

**Comment by QtEngineer** [comment]
Traceback (most recent call last):
  File "train_deep_sdf.py", line 1193, in <module>
    main_function(specs, system_specific_settings, results_folder, code_folder, train_split_file, test_split_file=test_split_file)
  File "train_deep_sdf.py", line 932, in main_function
    pred_sdf, extra_loss = decoder(inputs)
  File "/home/anaconda3/envs/whp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/whp/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/whp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patchnets-master/patchnets-master/code/networks/deep_sdf_decoder.py", line 942, in forward
    patch_recon[patch_mask] = 0.
IndexError: The shape of the mask [3072, 30] at index 1 does not match the shape of the indexed tensor [3072, 1] at index 1


The shape of patch_recon is [3072,1] while the shape of patch_mask is [3072,30]

**Comment by QtEngineer** [comment]
initialization_file = sdf_filename + "_init_" + str(patch_latent_size) + "_" + str(num_patches) + "_" + str(surface_sdf_threshold) + "_" + str(final_scaling_increase_factor)  + ("_tiny" if self.use_tiny_patchnet else "") + ".npy" # generated by train_deep_sdf.py

it seems that cant generate npyfile by train_deep_sdf.py though I set the sdf_file in deep_sdf_decoder.py

**Comment by QtEngineer** [comment]
I successfully trained the model ,but while reconstructing  same error occured :

file "deep_sdf_decoder.py"  
patch_recon[patch_mask] = 0.
IndexError: The shape of the mask [8000, 30] at index 1 does not match the shape of the indexed tensor [8000, 1] at index 1

**Comment by edgar-tr** [comment]
I didn't make the code user-friendly, so some of the settings depend on each other. This looks as if some settings are inconsistent with each other (I don't know which). You can take a look at the specs folder, it should contain an example for settings that use object latent codes.
