### ISSUE TITLE
How to get image of the learned patch distribution 

### ISSUE THREAD

**Issue by QtEngineer** [edgar-tr/patchnets#9]
like 【teaser.png】[https://raw.githubusercontent.com/edgar-tr/patchnets/master/misc/teaser.png](url)
Hi，sorry to trouble you . i wonder is it posiible to get the image from preoprocessed .npz file directly（through point cloud processing software）？If not, How to get the image from latent code,or by other way? Thank you!

**Comment by edgar-tr** [comment]
Please see https://github.com/edgar-tr/patchnets/blob/1d20bfd1ec74f8c6687939c6092642685fdeee94/useful_scripts.py#L1706

**Comment by QtEngineer** [comment]
Thanks a lot !
